# Alpaca API Configuration
ALPACA_API_KEY_LIVE = "AK2V88RDO5MYCFOE8FJH"
ALPACA_SECRET_KEY_LIVE = "gmCM49z9z3VlmTnoF7vsn9wliXZz6SE6NHCs5d5I"
ALPACA_API_KEY_PAPER = "AK2V88RDO5MYCFOE8FJH"
ALPACA_SECRET_KEY_PAPER = "gmCM49z9z3VlmTnoF7vsn9wliXZz6SE6NHCs5d5I"

# Data Feed Configuration
APCA_DATA_FEED = "iex"
APCA_PAPER = false

# Financial Modeling Prep API (for top volume stocks)
FMP_API_KEY = "anc5nLqF1PuZUQGhxDHpgXuU0Yp9Cj0V"

# Finnhub API (for fallback data)
FINNHUB_API_KEY = "your_finnhub_key_here"